#Site Settings
title: Thien Tran
email: ttran384@gatech.edu
description: A personal website showcasing Thien Tran (Thien Long Tran), a Computer Science student at the Georgia Institute of Technology.
github_username:  thienlongtran